version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: ${MONGODB_CONTAINER_NAME}
    restart: always
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DBNAME}
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: ${MONGODB_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
    networks:
      - mongodb_network
    depends_on:
      - mongodb

  velure_product_service:
    image: teste
    container_name: velure
    ports:
      - "${NESTJS_PORT}:${NESTJS_PORT}"
    environment:
      NESTJS_PORT: ${NESTJS_PORT}
      MONGODB_HOST: ${MONGODB_CONTAINER_NAME}
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_DBNAME: ${MONGODB_DBNAME}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    networks:
      - mongodb_network
    depends_on:
      - mongodb

networks:
  mongodb_network:

volumes:
  mongodb_data: